global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mdt-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  - job_name: 'mdt-ml'
    static_configs:
      - targets: ['ml:5000']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
